# This is the configuration file for catnip.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnip

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = " ", name = "user", color = "(RD)"}
hostname  = {icon = " ", name = "hostname", color = "(YW)"}
uptime    = {icon = " ", name = "uptime", color = "(BE)"}
distro    = {icon = " ", name = "distro", color = "(GN)"}
kernel    = {icon = " ", name = "kernel", color = "(MA)"}
desktop   = {icon = " ", name = "desktop", color = "(CN)"}
terminal  = {icon = " ", name = "term", color = "(RD)"}
shell     = {icon = " ", name = "shell", color = "(MA)"}
# gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}
# cpu       = {icon = " ", name = "cpu", color = "(RD)"}
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}
# memory    = {icon = " ", name = "memory", color = "(YW)"}
# The package and weather stats will increase the execution time of Catnip! Enable at your own discretion.
# packages  = {icon = " ", name = "packages", color = "(GN)"}
# weather   = {icon = " ", name = "weather", color = "(BE)"} # Requires cURL and an emoji font.
sep_color = "SEPARATOR"
colors    = {icon = " ", name = "colors", color = "!DT!", symbol = ""}

##############################################
##               Misc Config                ##
##############################################
[misc]
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path   = "/path/to/some/image.png" # Please only use absolute paths.
scale  = 18
margin = [2, 2, 3,]
