# This is the distro logos file for catnap.
# Here you can configure all distro logos 
# or add a new one.
#
# https://github.com/iinsertNameHere/catnap

# kitty here. you may need to change the margins if you change the amount of lines
[default]
margin = [1, 2, 3,]
art    = [
	"{YW} /| ､      ",
	"{WE}(°､ ｡ 7    ",
	"{MA} |､  ~ヽ   ",
	"{BK} じしf_,)〳",
]