name: test-catnap
on:
  push:
  pull_request:
jobs:
  test-catnap:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
    - name: 'Install Nim'
      uses: iffy/install-nim@v5
    - name: 'Setup Nim'
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Build Catnap'
      run: nim debug
    - name: 'Install Figlet'
      run: sudo apt-get install figlet
    - name: 'Run Tests'
      run: cd scripts && ./test-commandline-args.sh
